### ISSUE TITLE
Group idnumbers of > 100 chars will cause DB error

### ISSUE THREAD

**Issue by markward** [markward/enrol_autoenrol#3]
Since group idnumbers are generated dynamically they could potentially be more than 100 characters if the user set filter is large enough. Need to add a max length to the group idnumber generation.

**Comment by juerghoerner** [comment]
I think it is this error. Where to add a max length to the group idnumber ?? 

enrol_autoenrol
Fehler beim Lesen der Datenbank

Weitere Informationen über diesen Fehler

Debug info: ERROR: invalid input syntax for integer: ""
SELECT * FROM mdl_groups WHERE id = $1 
[array (
0 => '',
)]
Error code: dmlreadexception
Stack trace:
line 443 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 244 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 764 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 1305 of /lib/dml/moodle_database.php: call to pgsql_native_moodle_database->get_records_sql()
line 1278 of /lib/dml/moodle_database.php: call to moodle_database->get_records_select()
line 48 of /enrol/autoenrol/db/upgrade.php: call to moodle_database->get_records_list()
line 535 of /lib/upgradelib.php: call to xmldb_enrol_autoenrol_upgrade()
line 1615 of /lib/upgradelib.php: call to upgrade_plugins()
line 434 of /admin/index.php: call to upgrade_noncore()

**Comment by markward** [comment]
Hi Juerghoerner.

This looks like a separate issue to me, could you log a separate ticket giving a few more details about how you received the dmlreadexception you listed?

Thanks

Mark

**Comment by markward** [comment]
Resolved by ce5e378

Note that this could still result on collisions between groups where the idnumber is identical up to the 100th character. At this point the solutions to that problem seem worse than the cure.
