### ISSUE TITLE
Moving out of sub-folder?

### ISSUE THREAD

**Issue by scyrma** [markward/enrol_autoenrol#5]
Hi, 

Great to see autoenrol appear on github! Would it be possible to move all files up by one folder, out of enrol/autoenrol? Using a subfolder makes it hard to deploy (and upgrade) this plugin directly to a moodle site.

Thanks!

**Comment by markward** [comment]
I'm going to close this issue since it's been innactive for a couple of months and the structure works when using the sub-tree approach.

**Comment by scyrma** [comment]
Yes, sorry for not replying. Sub-tree clearly works and we're looking into it.
